package org.bbs.apklauncher.emb;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.Dialog;
import android.app.Fragment;
import android.app.ListActivity;
import android.app.TaskStackBuilder;
import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.content.res.Resources.Theme;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.os.Bundle;
import android.os.PersistableBundle;
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.ActionMode;
import android.view.ActionMode.Callback;
import android.view.ContextMenu;
import android.view.ContextMenu.ContextMenuInfo;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.View;
import android.view.accessibility.AccessibilityEvent;
import android.widget.ListView;
import android.support.v4.app.FragmentActivity;

@SuppressLint("NewApi")
public class Host_FragmentActivity extends FragmentActivity {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	Target_FragmentActivity mTargetActivity;
	


	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		mTargetActivity.onCreate(savedInstanceState);;
	}

	@Override
	public void onCreate(Bundle savedInstanceState,
			PersistableBundle persistentState) {
		super.onCreate(savedInstanceState, persistentState);
		mTargetActivity.onCreate(savedInstanceState, persistentState);
	}

//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	@Override
	protected void onRestoreInstanceState(Bundle savedInstanceState) {
		super.onRestoreInstanceState(savedInstanceState);
		mTargetActivity.onRestoreInstanceState(savedInstanceState);
	}

	@Override
	public void onRestoreInstanceState(Bundle savedInstanceState,
			PersistableBundle persistentState) {
		super.onRestoreInstanceState(savedInstanceState, persistentState);
		mTargetActivity.onRestoreInstanceState(savedInstanceState, persistentState);
	}

	@Override
	protected void onPostCreate(Bundle savedInstanceState) {
		super.onPostCreate(savedInstanceState);
		mTargetActivity.onPostCreate(savedInstanceState);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public void onPostCreate(Bundle savedInstanceState,
			PersistableBundle persistentState) {
		super.onPostCreate(savedInstanceState, persistentState);
		mTargetActivity.onPostCreate(savedInstanceState, persistentState);
	}

	@Override
	protected void onStart() {
		super.onStart();
		mTargetActivity.onStart();
	}

	@Override
	protected void onRestart() {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		super.onStart();
		mTargetActivity.onStart();
	}

	@Override
	protected void onResume() {
		super.onResume();
		mTargetActivity.onResume();
	}

	@Override
	protected void onPostResume() {
		super.onPostResume();
		mTargetActivity.onPostResume();
	}

	@Override
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	protected void onNewIntent(Intent intent) {
		super.onNewIntent(intent);
		mTargetActivity.onNewIntent(intent);
	}

	@Override
	protected void onSaveInstanceState(Bundle outState) {
		super.onSaveInstanceState(outState);
		mTargetActivity.onSaveInstanceState(outState);
	}

	@Override
	public void onSaveInstanceState(Bundle outState,
			PersistableBundle outPersistentState) {
		super.onSaveInstanceState(outState, outPersistentState);
		mTargetActivity.onSaveInstanceState(outState, outPersistentState);
	}
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template

	@Override
	protected void onPause() {
		super.onPause();
		mTargetActivity.onPause();
	}

	@Override
	protected void onUserLeaveHint() {
		super.onUserLeaveHint();
		mTargetActivity.onUserLeaveHint();
	}

	@Override
	public boolean onCreateThumbnail(Bitmap outBitmap, Canvas canvas) {
		boolean created =  super.onCreateThumbnail(outBitmap, canvas);
		return created ? true : mTargetActivity.onCreateThumbnail(outBitmap, canvas);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public CharSequence onCreateDescription() {
		CharSequence c =  super.onCreateDescription();
		return TextUtils.isEmpty(c) ? mTargetActivity.onCreateDescription() : c;
	}

	@Override
	public void onProvideAssistData(Bundle data) {
		super.onProvideAssistData(data);
		mTargetActivity.onProvideAssistData(data);
	}

	@Override
	protected void onStop() {
		super.onStop();
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		mTargetActivity.onStop();
	}

	@Override
	protected void onDestroy() {
		super.onDestroy();
		mTargetActivity.onDestroy();
	}

	@Override
	public void onConfigurationChanged(Configuration newConfig) {
		super.onConfigurationChanged(newConfig);
		mTargetActivity.onConfigurationChanged(newConfig);
	}
	// tag_end:No_FragmentActivity

	@Override
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	public void onLowMemory() {
		super.onLowMemory();
		mTargetActivity.onLowMemory();
	}

	@Override
	public void onTrimMemory(int level) {
		super.onTrimMemory(level);
		mTargetActivity.onTrimMemory(level);
	}

	@Override
	public void onAttachFragment(Fragment fragment) {
		super.onAttachFragment(fragment);
		mTargetActivity.onAttachFragment(fragment);
	}

//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	@Override
	public boolean onKeyDown(int keyCode, KeyEvent event) {
		boolean handled =  super.onKeyDown(keyCode, event);
		return !handled ? mTargetActivity.onKeyDown(keyCode, event) : handled;
	}

	@Override
	public boolean onKeyLongPress(int keyCode, KeyEvent event) {
		boolean handled =  super.onKeyLongPress(keyCode, event);
		return !handled ? mTargetActivity.onKeyLongPress(keyCode, event) : handled;
	}

	@Override
	public boolean onKeyUp(int keyCode, KeyEvent event) {
		boolean handled =  super.onKeyUp(keyCode, event);
		return !handled ? mTargetActivity.onKeyUp(keyCode, event) : handled;
	}
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template

	@Override
	public boolean onKeyMultiple(int keyCode, int repeatCount, KeyEvent event) {
		boolean handled =  super.onKeyMultiple(keyCode, repeatCount, event);
		return !handled ? mTargetActivity.onKeyMultiple(keyCode, repeatCount, event) : handled;
	}

	@Override
	public void onBackPressed() {
		super.onBackPressed();
//		mTargetActivity.onBackPressed();
	}

	@Override
	public boolean onKeyShortcut(int keyCode, KeyEvent event) {
		boolean handled =  super.onKeyShortcut(keyCode, event);
		return !handled ? mTargetActivity.onKeyShortcut(keyCode, event) : handled;
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public boolean onTouchEvent(MotionEvent event) {
		boolean handled =  super.onTouchEvent(event);
		return !handled ? mTargetActivity.onTouchEvent(event) : handled;
	}

	@Override
	public boolean onTrackballEvent(MotionEvent event) {
		boolean handled =  super.onTrackballEvent(event);
		return !handled ? mTargetActivity.onTrackballEvent(event) : handled;
	}

	@Override
	public boolean onGenericMotionEvent(MotionEvent event) {
		boolean handled =  super.onGenericMotionEvent(event);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		return !handled ? mTargetActivity.onGenericMotionEvent(event) : handled;
	}

	@Override
	public void onUserInteraction() {
		super.onUserInteraction();
		mTargetActivity.onUserInteraction();
	}

	@Override
	public void onWindowAttributesChanged(
			android.view.WindowManager.LayoutParams params) {
		super.onWindowAttributesChanged(params);
		mTargetActivity.onWindowAttributesChanged(params);
	}

	@Override
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	public void onContentChanged() {
		super.onContentChanged();
		mTargetActivity.onContentChanged();
	}

	@Override
	public void onWindowFocusChanged(boolean hasFocus) {
		super.onWindowFocusChanged(hasFocus);
		mTargetActivity.onWindowFocusChanged(hasFocus);
	}

	@Override
	public void onAttachedToWindow() {
		super.onAttachedToWindow();
		mTargetActivity.onAttachedToWindow();
	}

//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	@Override
	public void onDetachedFromWindow() {
		super.onDetachedFromWindow();
		mTargetActivity.onDetachedFromWindow();
	}

	@Override
	public boolean dispatchKeyEvent(KeyEvent event) {
		return super.dispatchKeyEvent(event);
	}

	@Override
	public boolean dispatchKeyShortcutEvent(KeyEvent event) {
		boolean handled =  super.dispatchKeyShortcutEvent(event);
		return !handled ? mTargetActivity.dispatchKeyShortcutEvent(event) : handled;
	}

//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	@Override
	public boolean dispatchTouchEvent(MotionEvent ev) {
		boolean handled =  super.dispatchTouchEvent(ev);
		return !handled ? mTargetActivity.dispatchTouchEvent(ev) : handled;
	}

	@Override
	public boolean dispatchTrackballEvent(MotionEvent ev) {
		boolean handled =  super.dispatchTouchEvent(ev);
		return !handled ? mTargetActivity.dispatchTrackballEvent(ev) : handled;
	}

	@Override
	public boolean dispatchGenericMotionEvent(MotionEvent ev) {
		boolean handled =  super.dispatchGenericMotionEvent(ev);
		return !handled ? mTargetActivity.dispatchGenericMotionEvent(ev) : handled;
	}
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template

	@Override
	public boolean dispatchPopulateAccessibilityEvent(AccessibilityEvent event) {
		boolean handled =  super.dispatchPopulateAccessibilityEvent(event);
		return !handled ? mTargetActivity.dispatchPopulateAccessibilityEvent(event) : handled;
	}

	@Override
	public View onCreatePanelView(int featureId) {
		return super.onCreatePanelView(featureId);
//		return super.onCreatePanelView(featureId);
	}

	@Override
	public boolean onCreatePanelMenu(int featureId, Menu menu) {
		return super.onCreatePanelMenu(featureId, menu);
//		return super.onCreatePanelMenu(featureId, menu);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public boolean onPreparePanel(int featureId, View view, Menu menu) {
		return super.onPreparePanel(featureId, view, menu);
//		return super.onPreparePanel(featureId, view, menu);
	}

	@Override
	public boolean onMenuOpened(int featureId, Menu menu) {
		return super.onMenuOpened(featureId, menu);
//		return super.onMenuOpened(featureId, menu);
	}

	@Override
	public boolean onMenuItemSelected(int featureId, MenuItem item) {
		// TODO Auto-generated method stub
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		return super.onMenuItemSelected(featureId, item);
	}

	@Override
	public void onPanelClosed(int featureId, Menu menu) {
		// TODO Auto-generated method stub
		super.onPanelClosed(featureId, menu);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// TODO Auto-generated method stub
		return super.onCreateOptionsMenu(menu);
	}

	@Override
	public boolean onPrepareOptionsMenu(Menu menu) {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		// TODO Auto-generated method stub
		return super.onPrepareOptionsMenu(menu);
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		// TODO Auto-generated method stub
		return super.onOptionsItemSelected(item);
	}

	@Override
	public boolean onNavigateUp() {
		return super.onNavigateUp();
	}

	@Override
	public boolean onNavigateUpFromChild(Activity child) {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		return super.onNavigateUpFromChild(child);
	}

	@Override
	public void onCreateNavigateUpTaskStack(TaskStackBuilder builder) {
		super.onCreateNavigateUpTaskStack(builder);
	}

	@Override
	public void onPrepareNavigateUpTaskStack(TaskStackBuilder builder) {
		super.onPrepareNavigateUpTaskStack(builder);
	}

	@Override
	public void onOptionsMenuClosed(Menu menu) {
		super.onOptionsMenuClosed(menu);
	}
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template

	@Override
	public void openOptionsMenu() {
		super.openOptionsMenu();
	}

	@Override
	public void closeOptionsMenu() {
		// TODO Auto-generated method stub
		super.closeOptionsMenu();
	}

	@Override
	public void onCreateContextMenu(ContextMenu menu, View v,
			ContextMenuInfo menuInfo) {
		// TODO Auto-generated method stub
		super.onCreateContextMenu(menu, v, menuInfo);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public boolean onContextItemSelected(MenuItem item) {
		// TODO Auto-generated method stub
		return super.onContextItemSelected(item);
	}

	@Override
	public void onContextMenuClosed(Menu menu) {
		// TODO Auto-generated method stub
		super.onContextMenuClosed(menu);
	}

	@Override
	protected Dialog onCreateDialog(int id) {
		// TODO Auto-generated method stub
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		return super.onCreateDialog(id);
	}

	@Override
	protected Dialog onCreateDialog(int id, Bundle args) {
		// TODO Auto-generated method stub
		return super.onCreateDialog(id, args);
	}

	@Override
	protected void onPrepareDialog(int id, Dialog dialog) {
		// TODO Auto-generated method stub
		super.onPrepareDialog(id, dialog);
	}

	@Override
	protected void onPrepareDialog(int id, Dialog dialog, Bundle args) {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		// TODO Auto-generated method stub
		super.onPrepareDialog(id, dialog, args);
	}

	@Override
	public boolean onSearchRequested() {
		// TODO Auto-generated method stub
		return super.onSearchRequested();
	}

	@Override
	protected void onApplyThemeResource(Theme theme, int resid, boolean first) {
		super.onApplyThemeResource(theme, resid, first);
		mTargetActivity.onApplyThemeResource(theme, resid, first);
	}

	@Override
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	public void overridePendingTransition(int enterAnim, int exitAnim) {
		super.overridePendingTransition(enterAnim, exitAnim);
		mTargetActivity.overridePendingTransition(enterAnim, exitAnim);
	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
		super.onActivityResult(requestCode, resultCode, data);
		mTargetActivity.onActivityResult(requestCode, resultCode, data);
	}

	@Override
	public void onActivityReenter(int resultCode, Intent data) {
		super.onActivityReenter(resultCode, data);
		mTargetActivity.onActivityReenter(resultCode, data);
	}

//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	@Override
	protected void onTitleChanged(CharSequence title, int color) {
		super.onTitleChanged(title, color);
		mTargetActivity.onTitleChanged(title, color);
	}

	@Override
	protected void onChildTitleChanged(Activity childActivity,
			CharSequence title) {
		super.onChildTitleChanged(childActivity, title);
		mTargetActivity.onChildTitleChanged(childActivity, title);
	}

	@Override
	public View onCreateView(String name, Context context, AttributeSet attrs) {
//		return super.onCreateView(name, context, attrs);
		return mTargetActivity.onCreateView(name, context, attrs);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}

	@Override
	public View onCreateView(View parent, String name, Context context,
			AttributeSet attrs) {
//		return super.onCreateView(parent, name, context, attrs);
		return mTargetActivity.onCreateView(parent, name, context, attrs);
	}

	@Override
	public void onVisibleBehindCanceled() {
		super.onVisibleBehindCanceled();
		mTargetActivity.onVisibleBehindCanceled();
	}

	@Override
	public void onEnterAnimationComplete() {
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
		super.onEnterAnimationComplete();
		mTargetActivity.onEnterAnimationComplete();
	}

	@Override
	public ActionMode onWindowStartingActionMode(Callback callback) {
		return super.onWindowStartingActionMode(callback);
	}

	@Override
	public void onActionModeStarted(ActionMode mode) {
		super.onActionModeStarted(mode);
	}

	@Override
	public void onActionModeFinished(ActionMode mode) {
		super.onActionModeFinished(mode);
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template
	}
	
		
	// tag_end:ListActivity
	
	// tag_start:FragmentActivity
	@Override
	public void onAttachFragment(android.support.v4.app.Fragment fragment) {
		super.onAttachFragment(fragment);
		mTargetActivity.onAttachFragment(fragment);
	}

	@Override
	protected void onResumeFragments() {
		super.onResumeFragments();
		mTargetActivity.onResumeFragments();
	}
//do NOT edit this file, auto-generated by createTemplage.groovy from Host_Activity.java.template

	@Override
	public Object onRetainCustomNonConfigurationInstance() {
		Object o = mTargetActivity.onRetainCustomNonConfigurationInstance();
		return o != null ? o : super.onRetainCustomNonConfigurationInstance();
	}
	// tag_end:FragmentActivity
}
